# Generated by Django 6.0.5 on 2026-09-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
